// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1jv0vniYav7zzOzNQfIhowG4zkandCxg',
    appId: '1:317241679287:web:6af49c8679bb62b5221c32',
    messagingSenderId: '317241679287',
    projectId: 'nmt-apd-assignment',
    authDomain: 'nmt-apd-assignment.firebaseapp.com',
    storageBucket: 'nmt-apd-assignment.appspot.com',
    measurementId: 'G-DL5P7VNQ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxpZ8kK6z_4ABXfbJlDu65GMxuzZuO4_o',
    appId: '1:317241679287:android:27580c7e510be8b0221c32',
    messagingSenderId: '317241679287',
    projectId: 'nmt-apd-assignment',
    storageBucket: 'nmt-apd-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8XKGL2ZKI7g-n__5pMsfP_Rc9EcEz0sE',
    appId: '1:317241679287:ios:94bd9f806c418e26221c32',
    messagingSenderId: '317241679287',
    projectId: 'nmt-apd-assignment',
    storageBucket: 'nmt-apd-assignment.appspot.com',
    iosBundleId: 'com.example.nmtApdpAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8XKGL2ZKI7g-n__5pMsfP_Rc9EcEz0sE',
    appId: '1:317241679287:ios:94bd9f806c418e26221c32',
    messagingSenderId: '317241679287',
    projectId: 'nmt-apd-assignment',
    storageBucket: 'nmt-apd-assignment.appspot.com',
    iosBundleId: 'com.example.nmtApdpAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1jv0vniYav7zzOzNQfIhowG4zkandCxg',
    appId: '1:317241679287:web:1e8be19005e69cab221c32',
    messagingSenderId: '317241679287',
    projectId: 'nmt-apd-assignment',
    authDomain: 'nmt-apd-assignment.firebaseapp.com',
    storageBucket: 'nmt-apd-assignment.appspot.com',
    measurementId: 'G-JE1TBFTGZ4',
  );
}
